plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.38'
}

version = '1.1.0'
group = 'com.example'

base {
    archivesName = 'throwabletnt'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    implementation "net.neoforged:neoforge:21.1.240"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
